#!/bin/zsh

set -e

mkdir -p ~/.color

background=(dark)
color=(edge)

zparseopts -K -- c:=color b:=background

echo $background[-1]
echo $color[-1]

cat - > ~/.color/alacritty.yml <<EOF
schemes:
  # Colors (Gruvbox light)
  gruvbox_light: &gruvbox_light
    # Default colors
    primary:
      # hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'

    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'
  # Colors (Gruvbox dark)
  gruvbox_dark: &gruvbox_dark
    primary:
      # hard contrast background - '#1d2021'
      background:        &gruvbox_dark_bg '#282828'
      # soft contrast background - '#32302f'
      foreground:        '#ebdbb2'
      bright_foreground: '#fbf1c7'
      dim_foreground:    '#a89984'
    cursor:
      text:   CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text:   CellBackground
      cursor: CellForeground
    # search:
    #   matches:
    #     foreground: '#000000'
    #     background: '#ffffff'
    #   focused_match:
    #    foreground: CellBackground
    #    background: CellForeground
    #   bar:
    #     background: ''
    #     foreground: ''
    # line_indicator:
    #   foreground: None
    #   background: None
    selection:
      text:       CellBackground
      background: CellForeground
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
    normal:
      black:   *gruvbox_dark_bg
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    dim:
      black:   '#32302f'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#928374'
    # indexed_colors: []
  ### Edge (Dark Default variant)
  edge_dark_def:  &edge_dark
    primary:
      background: "0x2c2e34"
      foreground: "0xc5cdd9"

    normal:
      black: "0x3e4249"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

    bright:
      black: "0x3e4249"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

  material: &material
    # Default colors
    primary:
      background: '#263238'
      foreground: '#eeffff'

    # Normal colors
    normal:
      black:   '#000000'  # Arbitrary
      red:     '#e53935'
      green:   '#91b859'
      yellow:  '#ffb62c'
      blue:    '#6182b8'
      magenta: '#ff5370'  # Dark pink of the original material theme
      cyan:    '#39adb5'
      white:   '#a0a0a0'  # Arbitrary

    # Bright colors
    bright:
      black:   '#4e4e4e'  # Arbitrary
      red:     '#ff5370'
      green:   '#c3e88d'
      yellow:  '#ffcb6b'
      blue:    '#82aaff'
      magenta: '#f07178'  # Pink of the original material theme
      cyan:    '#89ddff'
      white:   '#ffffff'  # Arbitrary
  solarized_light: &light
    primary:
      background: '0xfdf6e3' # base3
      foreground: '0x657b83' # base00
    cursor:
      text:   '0xfdf6e3' # base3
      cursor: '0x657b83' # base00
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3

  solarized_dark: &dark
    primary:
      background: '0x002b36' # base03
      foreground: '0x839496' # base0
    cursor:
      text:   '0x002b36' # base03
      cursor: '0x839496' # base0
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3

colors: *${color[-1]}_${background[-1]}
EOF

cat - > ~/.color/color.vim <<EOF
colorscheme ${color[-1]}
set background=${background[-1]}
EOF
