#!/bin/zsh

set -e

mkdir -p ~/.color

background=(dark)
color=(edge)

if [[ -f ~/.color/current ]]; then
  IFS=":" read -r color background  < ~/.color/current
  color=("$color")
  background=("$background")
fi

zparseopts -K -- c:=color b:=background

echo "${color[-1]}:${background[-1]}" > ~/.color/current

echo "${color[-1]}"
echo "${background[-1]}"

cat - > ~/.color/alacritty.yml <<EOF
schemes:
  # Colors (Gruvbox light)
  gruvbox_light: &gruvbox_light
    # Default colors
    primary:
      # hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'

    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'
  # Colors (Gruvbox dark)
  gruvbox_dark: &gruvbox_dark
    primary:
      # hard contrast background - '#1d2021'
      background:        &gruvbox_dark_bg '#282828'
      # soft contrast background - '#32302f'
      foreground:        '#ebdbb2'
      bright_foreground: '#fbf1c7'
      dim_foreground:    '#a89984'
    cursor:
      text:   CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text:   CellBackground
      cursor: CellForeground
    # search:
    #   matches:
    #     foreground: '#000000'
    #     background: '#ffffff'
    #   focused_match:
    #    foreground: CellBackground
    #    background: CellForeground
    #   bar:
    #     background: ''
    #     foreground: ''
    # line_indicator:
    #   foreground: None
    #   background: None
    selection:
      text:       CellBackground
      background: CellForeground
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
    normal:
      black:   *gruvbox_dark_bg
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    dim:
      black:   '#32302f'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#928374'
    # indexed_colors: []

  ### Edge (Light variant)
  edge_light:	  &edge_light
    primary:
      background: "0xfafafa"
      foreground: "0x4b505b"
  
    normal:
      black: "0x4b505b"
      red: "0xd05858"
      green: "0x608e32"
      yellow: "0xbe7e05"
      blue: "0x5079be"
      magenta: "0xb05ccc"
      cyan: "0x3a8b84"
      white: "0xfafafa"
  
    bright:
      black: "0x4b505b"
      red: "0xd05858"
      green: "0x608e32"
      yellow: "0xbe7e05"
      blue: "0x5079be"
      magenta: "0xb05ccc"
      cyan: "0x3a8b84"
      white: "0xfafafa"

  ### Edge (Dark Default variant)
  edge_dark_def:  &edge_dark
    primary:
      background: "0x2c2e34"
      foreground: "0xc5cdd9"
  
    normal:
      black: "0x3e4249"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"
  
    bright:
      black: "0x3e4249"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

  ### Edge (Dark Aura variant)
  edge_dark_aura:  &edge_dark_aura
    primary:
      background: "0x2b2d37"
      foreground: "0xc5cdd9"
  
    normal:
      black: "0x363a49"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"
  
    bright:
      black: "0x363a49"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

  ### Edge (Dark Neon variant)
  edge_dark_neon:  &edge_dark_neon
    primary:
      background: "0x2b2d3a"
      foreground: "0xc5cdd9"
  
    normal:
      black: "0x363a4e"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"
  
    bright:
      black: "0x363a4e"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

  material: &material
    # Default colors
    primary:
      background: '#263238'
      foreground: '#eeffff'

    # Normal colors
    normal:
      black:   '#000000'  # Arbitrary
      red:     '#e53935'
      green:   '#91b859'
      yellow:  '#ffb62c'
      blue:    '#6182b8'
      magenta: '#ff5370'  # Dark pink of the original material theme
      cyan:    '#39adb5'
      white:   '#a0a0a0'  # Arbitrary

    # Bright colors
    bright:
      black:   '#4e4e4e'  # Arbitrary
      red:     '#ff5370'
      green:   '#c3e88d'
      yellow:  '#ffcb6b'
      blue:    '#82aaff'
      magenta: '#f07178'  # Pink of the original material theme
      cyan:    '#89ddff'
      white:   '#ffffff'  # Arbitrary
  solarized_light: &light
    primary:
      background: '0xfdf6e3' # base3
      foreground: '0x657b83' # base00
    cursor:
      text:   '0xfdf6e3' # base3
      cursor: '0x657b83' # base00
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3

  solarized_dark: &dark
    primary:
      background: '0x002b36' # base03
      foreground: '0x839496' # base0
    cursor:
      text:   '0x002b36' # base03
      cursor: '0x839496' # base0
    normal:
      black:   '0x073642' # base02
      red:     '0xdc322f' # red
      green:   '0x859900' # green
      yellow:  '0xb58900' # yellow
      blue:    '0x268bd2' # blue
      magenta: '0xd33682' # magenta
      cyan:    '0x2aa198' # cyan
      white:   '0xeee8d5' # base2
    bright:
      black:   '0x002b36' # base03
      red:     '0xcb4b16' # orange
      green:   '0x586e75' # base01
      yellow:  '0x657b83' # base00
      blue:    '0x839496' # base0
      magenta: '0x6c71c4' # violet
      cyan:    '0x93a1a1' # base1
      white:   '0xfdf6e3' # base3

  # Mapping 'dark' to default color scheme 'storm'
  tokyonight_storm: &tokyonight_dark
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xc0caf5'

    # Normal colors
    normal:
      black:   '0x1D202F'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xa9b1d6'

    # Bright colors
    bright:
      black:   '0x414868'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xc0caf5'

    indexed_colors:
      - { index: 16, color: '0xff9e64' }
      - { index: 17, color: '0xdb4b4b' }

  tokyonight_light: &tokyonight_light
    # Default colors
    primary:
      background: '0xe1e2e7'
      foreground: '0x3760bf'

    # Normal colors
    normal:
      black:   '0xe9e9ed'
      red:     '0xf52a65'
      green:   '0x587539'
      yellow:  '0x8c6c3e'
      blue:    '0x2e7de9'
      magenta: '0x9854f1'
      cyan:    '0x007197'
      white:   '0x6172b0'

    # Bright colors
    bright:
      black:   '0xa1a6c5'
      red:     '0xf52a65'
      green:   '0x587539'
      yellow:  '0x8c6c3e'
      blue:    '0x2e7de9'
      magenta: '0x9854f1'
      cyan:    '0x007197'
      white:   '0x3760bf'

    indexed_colors:
      - { index: 16, color: '0xb15c00' }
      - { index: 17, color: '0xc64343' }

  onehalf_light: &onehalf_light
    primary:
      background: '0xfafafa'
      foreground: '0x383a42'

    normal:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'

    bright:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'

  onehalf_dark: &onehalf_dark
    primary:
      background: '0x282c34'
      foreground: '0xdcdfe4'

    normal:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'

    bright:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'

  papercolor_light: &papercolor_light
    # Default colors
    primary:
      background: '0xeeeeee'
      foreground: '0x878787'

    cursor:
      text: '0xeeeeee'
      cursor: '0x878787'

    # Normal colors
    normal:
      black:   '0xeeeeee'
      red:     '0xaf0000'
      green:   '0x008700'
      yellow:  '0x5f8700'
      blue:    '0x0087af'
      magenta: '0x878787'
      cyan:    '0x005f87'
      white:   '0x444444'

    # Bright colors
    bright:
      black:   '0xbcbcbc'
      red:     '0xd70000'
      green:   '0xd70087'
      yellow:  '0x8700af'
      blue:    '0xd75f00'
      magenta: '0xd75f00'
      cyan:    '0x005faf'
      white:   '0x005f87'

  papercolor_dark: &papercolor_dark
    # Default colors
    primary:
      background: '0x1c1c1c'
      foreground: '0x808080'

    cursor:
      text: '0x1c1c1c'
      cursor: '0x808080'

    # Normal colors
    normal:
      black:   '0x1c1c1c'
      red:     '0xaf005f'
      green:   '0x5faf00'
      yellow:  '0xd7af5f'
      blue:    '0x5fafd7'
      magenta: '0x808080'
      cyan:    '0xd7875f'
      white:   '0xd0d0d0'

    # Bright colors
    bright:
      black:   '0x585858'
      red:     '0x5faf5f'
      green:   '0xafd700'
      yellow:  '0xaf87d7'
      blue:    '0xffaf00'
      magenta: '0xffaf00'
      cyan:    '0x00afaf'
      white:   '0x5f8787'

colors: *${color[-1]}_${background[-1]}
EOF

# TODO(kaihowl) remove when #326 is fixed
# Force Reload for older alacritty versions that do not file watch imports
echo "###ForceReload" >> "$DOTS/alacritty/config--alacritty--alacritty.yml.symlink"
sed -i.backup "/###ForceReload/d" "$DOTS/alacritty/config--alacritty--alacritty.yml.symlink"

vim_colorscheme=${color[-1]}

if [[ $vim_colorscheme = onehalf ]]; then
  vim_colorscheme="onehalf${background[-1]}"
fi

cat - > ~/.color/color.vim <<EOF
let g:edge_enable_italic = 1
let g:edge_disable_italic_comment = 0
let g:edge_diagnostic_line_highlight = 1
let g:edge_better_performance = 1
colorscheme ${vim_colorscheme}
set background=${background[-1]}
EOF
