#!/bin/bash
set -e
set -x

# Run all dotfiles installers.
export DOTS=$HOME/.dotfiles

cd "$(dirname "$0")"/..

if [[ "$(uname)" == "Linux" && "$(lsb_release -i)" == *"Ubuntu"* ]]; then
  sudo apt-get update
fi

# No explicit update for homebrew, there are enough update and cleanup
# invocations automatically after a certain time has passed.

# find the installers and run them iteratively
installers=$(find . -name install.sh)
for installer in ${installers}; do
  echo -e "Running \e[32m${installer}\e[0m"
  sh -c "${installer}"
done
