#!/bin/bash
set -e

cd "$(dirname "$0")"/..

source common/perf_stubs.sh

if [[ "$(uname)" == "Linux" && "$(lsb_release -i)" == *"Ubuntu"* ]]; then
  source common/apt.sh
  apt_update
fi

if [[ "$(uname)" == *"Darwin"* ]] && [[ "$(xcode-select -p)" == *"CommandLineTools"* ]]; then
  # Full XCode is for example needed to compile pynvim's greenlet
  printf "Running \e[32mFull XCode install needed\e[0m"
  exit 1
fi

# No explicit update for homebrew, there are enough update and cleanup
# invocations automatically after a certain time has passed.

# find the installers and run them iteratively
# Run zsh install first
# If there are more dependencies between installers in the future,
# this needs to be expanded.
installers=$(find . -name zsh -prune -o -name install.sh -print)
installers="./zsh/install.sh $installers"
for installer in ${installers}; do
  printf "Running \e[32m%s\e[0m" "${installer}"
  START=$(date +%s)
  sh -c "${installer}"
  END=$(date +%s)
  DURATION=$((END - START))
  add_measurement "${installer}" $DURATION || true
done
