#!/bin/bash

# Run all test scripts

cd "$(dirname "$0")"/..

# Needed to bring the correct PATH in place such that the /usr/bin/env shebang
# for the test scripts finds a working zsh
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# find all test scripts and run them
tests=("${(@f)$(find . -name "test.sh")}")
for t in $tests; do
  printf "Running \e[32m%s\e[0m" "${t}"
  zsh -c -i -l "${t}"
done

# check for missing licenses
./script/license_check.py
