#!/bin/zsh -ie

# Run all test scripts

cd "$(dirname "$0")"/..

# find all test scripts and run them
tests=("${(@f)$(find . -name "test.sh")}")
for t in $tests; do
  printf "Running \e[32m%s\e[0m" "${t}"
  zsh -c -i "${t}"
done
