#!/bin/bash

# Run all test scripts

cd "$(dirname "$0")"/.. || exit 1

# Needed to bring the correct PATH in place such that the /usr/bin/env shebang
# for the test scripts finds a working zsh
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  # shellcheck disable=SC1090,SC1091
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# find all test scripts and run them
tests=()
if [[ $DOTFILES_PROFILE != minimal ]]; then
  while IFS= read -r -d '' test; do
      tests+=("$test")
  done < <(find . -type f -name 'test.sh' -print0)
else
  # Tests for minimal configuration
  tests=(colors/test.sh efm/test.sh fzf/test.sh git/test.sh nvim/test.sh revup/test.sh ripgrep/test.sh shellcheck/test.sh tmux/test.sh vint/test.sh virtualenvwrapper/test.sh zsh/test.sh)
fi

failed_tests=0
for t in "${tests[@]}"; do
  printf "Running \e[32m%s\e[0m\n" "${t}"
  if ! timeout 60s zsh -i "${t}"; then
      echo "ERROR: TEST ${t} FAILED"
      ((failed_tests+=1))
  fi
done

if [[ $failed_tests -ne 0 ]]; then
    echo "FOUND ${failed_tests} FAILED TESTS"
    exit 1
fi

# check nix licenses
nix flake check --impure 
