# This tmux statusbar config was created by tmuxline.vim
# on Fr, 01 Jan 2021

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#dcdfe4,bg=#5d677a"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#98c379"
set -g status-style "none,bg=#313640"
set -g message-style "fg=#dcdfe4,bg=#5d677a"
set -g pane-border-style "fg=#5d677a"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#98c379,bg=#313640"
set -g status-left "#[fg=#282c34,bg=#98c379] #S #[fg=#98c379,bg=#313640,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#5d677a,bg=#313640,nobold,nounderscore,noitalics]#[fg=#dcdfe4,bg=#5d677a] %Y-%m-%d | %H:%M #[fg=#98c379,bg=#5d677a,nobold,nounderscore,noitalics]#[fg=#282c34,bg=#98c379] #h "
setw -g window-status-format "#[fg=#98c379,bg=#313640] #I |#[fg=#98c379,bg=#313640] #W "
setw -g window-status-current-format "#[fg=#313640,bg=#5d677a,nobold,nounderscore,noitalics]#[fg=#dcdfe4,bg=#5d677a] #I |#[fg=#dcdfe4,bg=#5d677a] #W #[fg=#5d677a,bg=#313640,nobold,nounderscore,noitalics]"
