name: 'Install git-perf'
description: 'Install git-perf binary'
runs:
  using: "composite"
  steps:
    - id: install
      run: |
        mkdir -p ~/.git-perf/
        pushd ~/.git-perf
        os=$(uname -s)
        # TODO(kaihowl) install latest
        if [ $os = "Linux" ]; then
          gitperf_url="https://github.com/kaihowl/git-perf/releases/download/0.14.0/gitperf-0.14.0-x86_64-unknown-linux-musl.tar.gz"
        elif [ $os = "Darwin" ]; then
          gitperf_url="https://github.com/kaihowl/git-perf/releases/download/0.14.0/gitperf-0.14.0-x86_64-apple-darwin.tar.gz"
        else
          echo "Unsupported OS"
          exit 1
        fi
        curl -L "$gitperf_url" | tar -xz --strip-components=1
        echo "$HOME/.git-perf" >> $GITHUB_PATH
      shell: bash
